name: Generate Sitemap
on:
  push:
    branches: [release-prod]

jobs:
  sitemap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://eonechomedia.com/
      
      - uses: EndBug/add-and-commit@v9
        with:
          message: "Auto update sitemap"